extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:node/recommended
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
plugins:
  - prettier
  - node
env:
  node: true
  browser: true
root: true
rules:
  import/extensions: 'off'
  import/prefer-default-export: 'off'
  max-len: 'off'
  curly: 'error'
  object-curly-newline: 'off'
  operator-linebreak: 'off'
  prefer-arrow-callback: 'error'
  prettier/prettier: 'error'
  node/no-unsupported-features/es-syntax: 'off'
  node/no-missing-import: 'off'
  node/no-missing-require: 'off'
  node/shebang: 'off'
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - err # Error decoration
        - obj # .reduce() object
        - pkg # Package instance
        - req
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-shadow': 'off'
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/no-explicit-any': 'error'
  '@typescript-eslint/comma-dangle': 'off'
  react/jsx-one-expression-per-line: 'off'
  react/prop-types: 'off'
  react/jsx-props-no-spreading: 'off'
  jsx-a11y/anchor-is-valid: 'off'
overrides:
  - files:
      - '**/__tests__/**'
      - '**/__mocks__/**'
      - '**/__helpers__/**'
      - '**/*.js'
    rules:
      import/no-extraneous-dependencies: 'off'
      no-console: 'off'
      no-param-reassign: 'off'
      node/no-extraneous-import: 'off'
      node/no-extraneous-require: 'off'
      node/no-unpublished-import: 'off'
      strict: 'off'
      '@typescript-eslint/no-explicit-any': 'warn'
    extends:
      - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    pragma: React
    version: detect
