name: CI

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == refs/heads/master
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy Preview
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 