name: CI

on: [push]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Setup
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Setup
        run: yarn
      - name: Build
        run: yarn build
  deploy-branch:
    name: Deploy Branch
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Setup
        run: yarn
      # - name: Migrate Database
      #   run: yarn migrate:remote
      #   env:
      #     SQL_PORT: 3306
      #     SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      #     SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      #     SQL_USER: ${{ secrets.SQL_USER }}
      #     SQL_HOST: ${{ secrets.SQL_HOST }}
      # - name: Seed Database
      #   run: yarn seed:remote
      #   env:
      #     SQL_PORT: 3306
      #     SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      #     SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      #     SQL_USER: ${{ secrets.SQL_USER }}
      #     SQL_HOST: ${{ secrets.SQL_HOST }}
      #     ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      #     ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      - name: Deploy Preview
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          alias-domains: "{{BRANCH}}.canvasv2.lukeshay.vercel.app"
